feat: add search to transport table
routelink/client pull request #113
Opened 2024-04-27 17:32 UTC by Sableuze

Closes #

2024-04-28 21:01 UTC, olegnowikow requested changes

2024-04-28 21:01 UTC, olegnowikow commented on src/ui/search/SearchField.tsx
> +        <Typography variant="body2" sx={{ mr: '20px' }}>
remove padding and use [Stack](https://mui.com/material-ui/react-stack/) or `rem`

2024-04-29 14:02 UTC, Sableuze commented on src/stores/transport/transport.ts
> +    if (payload?.search === 'b')
Zaglushka

2024-05-01 13:14 UTC, olegnowikow approved these changes

2024-05-01 13:15 UTC, merged