feat: add and improve components, add new stores
routelink/client pull request #115
Opened 2024-04-28 08:16 UTC by TheKenkei

Closes #75 #74 

add new package: `react-helmet`

improve : `App`, `Maps`, `Sidebar` components
add new components: `Error`, `Loading`

improve  `app` store
add new stores : `title`, `maps`, `links`

delete unused `OtherComponent`

add new styles to `theme.tsx`

chore: refractor code with `prettier`

2024-04-28 20:56 UTC, olegnowikow requested changes
use [notistack](https://notistack.com/features/basic#maximum-snackbars)

2024-04-28 20:56 UTC, olegnowikow commented on src/App.tsx
> +              <meta charSet="utf-8" />
Why is this here?
Charset is defined in `index.html`

2024-04-28 20:56 UTC, olegnowikow commented on src/App.tsx
> +              <link rel="canonical" href="http://mysite.com/example" />
same things in `index.html`

2024-04-29 07:13 UTC, TheKenkei commented
@olegnowikow the error store stores only one error. Using [notistack](https://notistack.com/features/basic#maximum-snackbars) is impractical

2024-05-01 13:25 UTC, olegnowikow approved these changes

2024-05-01 13:27 UTC, merged