fix: incorrect position Modal component
routelink/client pull request #116
Opened 2024-04-28 17:47 UTC by TheKenkei

Closes #73 

https://github.com/routelink/client/assets/100131721/1a80a1f8-8588-476f-b0ad-2bfb670316b7

2024-04-28 20:42 UTC, olegnowikow requested changes

2024-04-28 20:42 UTC, olegnowikow commented on src/components/Modal/Modal.tsx
> +            id="ddd"
remove

2024-04-29 07:11 UTC, TheKenkei commented
@olegnowikow, please look at my edits

2024-05-01 13:01 UTC, olegnowikow approved these changes

2024-05-01 13:01 UTC, merged