update `users` components
routelink/client pull request #131
Opened 2024-05-05 10:41 UTC by JSFSchaikaai

* fix: remove unused variable
* fix: temp fix incorrect pagination (remove variant "all")
* fix: remove custom colors

2024-05-09 18:39 UTC, olegnowikow requested changes

2024-05-09 18:39 UTC, olegnowikow commented on src/components/Users/Users.tsx
> +                  {' '}
это для чего?

2024-05-12 10:10 UTC, olegnowikow commented on src/components/Users/Users.tsx
> +                  {' '}
`{' '}` - вот это зачем?)

2024-05-12 16:12 UTC, JSFSchaikaai commented
Самому интересно :)
Эту часть (и многие другие) я изначально делал без подобный вставок. А уже после комита... они появлялись. Виталий говорит, что это какой-то из наших плагинов делает автоматом (пробелы оборачивает или еще что-то).

2024-05-12 16:44 UTC, olegnowikow commented
> Самому интересно :) Эту часть (и многие другие) я изначально делал без подобный вставок. А уже после комита... они появлялись. Виталий говорит, что это какой-то из наших плагинов делает автоматом (пробелы оборачивает или еще что-то).

Фиксани этот момент и я сливаю)

2024-05-12 17:06 UTC, olegnowikow approved these changes

2024-05-12 17:06 UTC, merged

2024-05-13 17:02 UTC, TheKenkei commented
@JSFSchaikaai @olegnowikow у меня предположение что это делает `prettier`